---
title: "data import"
output: github_document
---

## data import: CSVs


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

let's import data using the 'readr' package
1. write the right path to find the data (relative path)
2. package name :: function name
```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```
look at the data
```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r}
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```

read_csv options
```{r}
read_csv("data/FAS_litters.csv",na = c("","NA",999,88),skip = 2)
```

## Other file formats
we need to read in an excel spreadsheet

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r}
lotr_words_df=
  read_excel(
    "data/lotR_Words.xlsx",
    range='B3:D6'
  )
```

## Still more formats

read in a sas dataset

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


## Data export

```{r}
write_csv(litters_df, file="result/lotr_words_df.csv")
```

## why not base r

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("weight"))
```
## 前两列放前面，其他的放后面用everything(),没有everything就只选择被select的两列
```{r}
select(litters_data,litter_number,pups_survive, everything())
```

```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```












 
